### ISSUE TITLE
Naming parameters in path

### ISSUE THREAD

**Issue by pir2o61** [giraffe-fsharp/Giraffe.OpenApi#6]
Is there a way to name parameters in path?
Something like `{petId:%i}` in https://github.com/hvester/EndpointBuilder will be very nice.

**Comment by mrtz-j** [comment]
Yes, that would indeed be possible. I can get the routef's parameters from the `routeHandler` like this:

```fsharp
let handlerType = routeHandler.GetType()
let handlerMethod = handlerType.GetMethods()[0]
let parameters = handlerMethod.GetParameters()
// Returns `Parameters: [|Int32 petId|]` for the route: 
// routef "/%i" (fun (petId: int) -> text $"PetId %i{petId}")
```

But I'm not sure how to get them for tuples e.g "/%i/%s", which just gives a `tupledArg`.

**Comment by pir2o61** [comment]
Yes, but it is just the way to get the parameters. I would like to put them in swagger:
![image](https://github.com/user-attachments/assets/1b1786e0-8eff-4606-a96d-c5c0f56c2d13)

I was looking around and probably there is a way via changing the convertToRouteTemplate in EndpointRouting.fs in (main) Giraffe. So will close it here, and when have sth ready will try there.

Thanks for response and work on this project :)
